// <auto-generated />
using System;
using System.Collections.Generic;
using JealPrototype.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JealPrototype.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226220646_Story3_5_Add_SyncType_Index")]
    partial class Story3_5_Add_SyncType_Index
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JealPrototype.Domain.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId");

                    b.ToTable("blog", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<string>("FeaturedImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("featured_image_url");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId")
                        .HasDatabaseName("idx_blog_post_dealership_id");

                    b.HasIndex("Slug")
                        .HasDatabaseName("idx_blog_post_slug");

                    b.HasIndex("DealershipId", "Slug")
                        .IsUnique();

                    b.ToTable("blog_post", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.Dealership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BodyBackgroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("body_background_color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text")
                        .HasColumnName("facebook_url");

                    b.Property<string>("FinancePolicy")
                        .HasColumnType("text")
                        .HasColumnName("finance_policy");

                    b.Property<string>("FinancePromoImage")
                        .HasColumnType("text")
                        .HasColumnName("finance_promo_image");

                    b.Property<string>("FinancePromoText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("finance_promo_text");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("font_family");

                    b.Property<string>("HeroBackgroundImage")
                        .HasColumnType("text")
                        .HasColumnName("hero_background_image");

                    b.Property<List<string>>("HeroCarouselImages")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("hero_carousel_images")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("HeroSubtitle")
                        .HasColumnType("text")
                        .HasColumnName("hero_subtitle");

                    b.Property<string>("HeroTitle")
                        .HasColumnType("text")
                        .HasColumnName("hero_title");

                    b.Property<string>("HeroType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hero_type");

                    b.Property<string>("HeroVideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("hero_video_url");

                    b.Property<string>("Hours")
                        .HasColumnType("text")
                        .HasColumnName("hours");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text")
                        .HasColumnName("instagram_url");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NavigationConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("navigation_config");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("SecondaryThemeColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("secondary_theme_color");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("theme_color");

                    b.Property<string>("WarrantyPolicy")
                        .HasColumnType("text")
                        .HasColumnName("warranty_policy");

                    b.Property<string>("WarrantyPromoImage")
                        .HasColumnType("text")
                        .HasColumnName("warranty_promo_image");

                    b.Property<string>("WarrantyPromoText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("warranty_promo_text");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteUrl")
                        .IsUnique()
                        .HasDatabaseName("idx_dealership_website_url");

                    b.ToTable("dealership", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.DealershipSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<bool>("EasyCarAutoSyncEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("easycar_auto_sync_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId")
                        .IsUnique()
                        .HasDatabaseName("idx_dealership_settings_dealership_id");

                    b.HasIndex("EasyCarAutoSyncEnabled")
                        .HasDatabaseName("idx_dealership_settings_auto_sync")
                        .HasFilter("easycar_auto_sync_enabled = TRUE");

                    b.ToTable("dealership_settings", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.DesignTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyBackgroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("body_background_color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("font_family");

                    b.Property<bool>("IsPreset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_preset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SecondaryThemeColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("secondary_theme_color");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("theme_color");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId");

                    b.ToTable("design_templates", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.EasyCarsCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumberEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number_encrypted");

                    b.Property<string>("AccountSecretEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_secret_encrypted");

                    b.Property<string>("ClientIdEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id_encrypted");

                    b.Property<string>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_secret_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("EncryptionIV")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encryption_iv");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("YardCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("yard_code");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId")
                        .IsUnique()
                        .HasDatabaseName("idx_easycars_credentials_dealership");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_easycars_credentials_active")
                        .HasFilter("is_active = true");

                    b.ToTable("dealership_easycars_credentials", null, t =>
                        {
                            t.HasCheckConstraint("CK_easycars_credentials_environment", "environment IN ('Test', 'Production')");
                        });
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.EasyCarsStockData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("1.0")
                        .HasColumnName("api_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StockItemJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stock_item_json");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("SyncedAt")
                        .HasDatabaseName("idx_easycar_stock_data_synced_at");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("idx_easycar_stock_data_vehicle_id_unique");

                    b.ToTable("easycar_stock_data", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.EasyCarsSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("1.0")
                        .HasColumnName("api_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<long>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessages")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("error_messages");

                    b.Property<int>("ItemsFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("items_failed");

                    b.Property<int>("ItemsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("items_processed");

                    b.Property<int>("ItemsSucceeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("items_succeeded");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SyncType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sync_type");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId")
                        .HasDatabaseName("idx_easycar_sync_logs_dealership_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_easycar_sync_logs_status");

                    b.HasIndex("SyncedAt")
                        .HasDatabaseName("idx_easycar_sync_logs_synced_at");

                    b.HasIndex("DealershipId", "SyncType", "SyncedAt")
                        .HasDatabaseName("idx_easycar_sync_logs_dealership_type_time");

                    b.ToTable("easycar_sync_logs", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.HeroMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId");

                    b.ToTable("hero_media", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("data_source");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("EasyCarsCustomerNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("easycars_customer_no");

                    b.Property<string>("EasyCarsLeadNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("easycars_lead_number");

                    b.Property<string>("EasyCarsRawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("easycars_raw_data");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("FinanceInterested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("finance_interested");

                    b.Property<DateTime?>("LastSyncedFromEasyCars")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_from_easycars");

                    b.Property<DateTime?>("LastSyncedToEasyCars")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_to_easycars");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Rating")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehicleInterestType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_interest_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_lead_created_at");

                    b.HasIndex("DataSource")
                        .HasDatabaseName("idx_leads_data_source");

                    b.HasIndex("DealershipId")
                        .HasDatabaseName("idx_lead_dealership_id");

                    b.HasIndex("EasyCarsLeadNumber")
                        .HasDatabaseName("idx_leads_easycars_lead")
                        .HasFilter("easycars_lead_number IS NOT NULL");

                    b.HasIndex("VehicleId");

                    b.ToTable("lead", null, t =>
                        {
                            t.HasCheckConstraint("CK_lead_data_source", "data_source IN ('Manual', 'EasyCars', 'WebForm')");
                        });
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.PromotionalPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("link_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId");

                    b.ToTable("promotional_panel", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.SalesRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalMessage")
                        .HasColumnType("text")
                        .HasColumnName("additional_message");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("Kilometers")
                        .HasColumnType("integer")
                        .HasColumnName("kilometers");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_sales_request_created_at");

                    b.HasIndex("DealershipId")
                        .HasDatabaseName("idx_sales_request_dealership_id");

                    b.ToTable("sales_request", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("system_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "easycar_sync_enabled",
                            CreatedAt = new DateTime(2026, 2, 26, 22, 6, 39, 113, DateTimeKind.Utc).AddTicks(8670),
                            Description = "Global toggle for all EasyCars stock synchronization",
                            UpdatedAt = new DateTime(2026, 2, 26, 22, 6, 39, 113, DateTimeKind.Utc).AddTicks(8672),
                            Value = "true"
                        },
                        new
                        {
                            Key = "easycar_sync_cron",
                            CreatedAt = new DateTime(2026, 2, 26, 22, 6, 39, 113, DateTimeKind.Utc).AddTicks(8674),
                            Description = "Cron expression for sync schedule (default: 2 AM daily)",
                            UpdatedAt = new DateTime(2026, 2, 26, 22, 6, 39, 113, DateTimeKind.Utc).AddTicks(8674),
                            Value = "0 2 * * *"
                        },
                        new
                        {
                            Key = "easycar_sync_concurrency",
                            CreatedAt = new DateTime(2026, 2, 26, 22, 6, 39, 113, DateTimeKind.Utc).AddTicks(8674),
                            Description = "Max concurrent dealership syncs (1=sequential)",
                            UpdatedAt = new DateTime(2026, 2, 26, 22, 6, 39, 113, DateTimeKind.Utc).AddTicks(8675),
                            Value = "1"
                        },
                        new
                        {
                            Key = "easycar_image_sync_enabled",
                            CreatedAt = new DateTime(2026, 2, 26, 22, 6, 39, 113, DateTimeKind.Utc).AddTicks(8675),
                            Description = "Enable/disable image sync during stock sync (default: true)",
                            UpdatedAt = new DateTime(2026, 2, 26, 22, 6, 39, 113, DateTimeKind.Utc).AddTicks(8675),
                            Value = "true"
                        });
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId")
                        .HasDatabaseName("idx_app_user_dealership_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_app_user_username");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("body");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("data_source");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer")
                        .HasColumnName("dealership_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DoorCount")
                        .HasColumnType("integer")
                        .HasColumnName("door_count");

                    b.Property<string>("EasyCarsRawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("easycars_raw_data");

                    b.Property<string>("EasyCarsStockNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("easycars_stock_number");

                    b.Property<string>("EasyCarsVIN")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("easycars_vin");

                    b.Property<string>("EasyCarsYardCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("easycars_yard_code");

                    b.Property<string>("EngineCapacity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("engine_capacity");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exterior_color");

                    b.Property<string>("Features")
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<string>("FuelType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("GearType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gear_type");

                    b.Property<List<string>>("Images")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("images")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("interior_color");

                    b.Property<DateTime?>("LastSyncedFromEasyCars")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_from_easycars");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("DataSource")
                        .HasDatabaseName("idx_vehicles_data_source");

                    b.HasIndex("DealershipId")
                        .HasDatabaseName("idx_vehicle_dealership_id");

                    b.HasIndex("EasyCarsStockNumber")
                        .HasDatabaseName("idx_vehicles_easycars_stock")
                        .HasFilter("easycars_stock_number IS NOT NULL");

                    b.HasIndex("EasyCarsVIN")
                        .HasDatabaseName("idx_vehicles_easycars_vin")
                        .HasFilter("easycars_vin IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_vehicle_status");

                    b.HasIndex("DealershipId", "Status")
                        .HasDatabaseName("idx_vehicle_dealership_status");

                    b.ToTable("vehicle", null, t =>
                        {
                            t.HasCheckConstraint("CK_vehicle_data_source", "data_source IN ('Manual', 'EasyCars', 'Import')");
                        });
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.Blog", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.BlogPost", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.DealershipSettings", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.DesignTemplate", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.EasyCarsCredential", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.EasyCarsStockData", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.EasyCarsSyncLog", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.HeroMedia", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.Lead", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Leads")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JealPrototype.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dealership");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.PromotionalPanel", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.SalesRequest", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.User", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Users")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("JealPrototype.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Vehicles")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("JealPrototype.Domain.Entities.Dealership", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("Users");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
