CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE dealership (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    logo_url text,
    address text NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(255) NOT NULL,
    hours text,
    about text,
    website_url character varying(255),
    finance_policy text,
    warranty_policy text,
    hero_background_image text,
    hero_type character varying(20) NOT NULL,
    hero_video_url text,
    hero_carousel_images jsonb NOT NULL DEFAULT ('[]'::jsonb),
    hero_title text,
    hero_subtitle text,
    theme_color character varying(7) NOT NULL,
    secondary_theme_color character varying(7) NOT NULL,
    body_background_color character varying(7) NOT NULL,
    font_family character varying(100) NOT NULL,
    navigation_config jsonb,
    facebook_url text,
    instagram_url text,
    finance_promo_image text,
    finance_promo_text character varying(500),
    warranty_promo_image text,
    warranty_promo_text character varying(500),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_dealership" PRIMARY KEY (id)
);

CREATE TABLE app_user (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) NOT NULL,
    password_hash text NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    user_type character varying(50) NOT NULL,
    dealership_id integer,
    permissions jsonb NOT NULL DEFAULT ('[]'::jsonb),
    created_by integer,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_app_user" PRIMARY KEY (id),
    CONSTRAINT "FK_app_user_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE blog (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    image_url text,
    published_date timestamp with time zone NOT NULL,
    author character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_blog" PRIMARY KEY (id),
    CONSTRAINT "FK_blog_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE blog_post (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    content text NOT NULL,
    excerpt text,
    featured_image_url text,
    author_name character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    published_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_blog_post" PRIMARY KEY (id),
    CONSTRAINT "FK_blog_post_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE dealership_easycars_credentials (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    account_number_encrypted text NOT NULL,
    account_secret_encrypted text NOT NULL,
    encryption_iv text NOT NULL,
    environment character varying(20) NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    yard_code character varying(50),
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_dealership_easycars_credentials" PRIMARY KEY (id),
    CONSTRAINT "CK_easycars_credentials_environment" CHECK (environment IN ('Test', 'Production')),
    CONSTRAINT "FK_dealership_easycars_credentials_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE design_templates (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer,
    name character varying(100) NOT NULL,
    description character varying(500),
    theme_color character varying(7) NOT NULL,
    secondary_theme_color character varying(7) NOT NULL,
    body_background_color character varying(7) NOT NULL,
    font_family character varying(100) NOT NULL,
    is_preset boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_design_templates" PRIMARY KEY (id),
    CONSTRAINT "FK_design_templates_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE hero_media (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    media_type character varying(50) NOT NULL,
    media_url text,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_hero_media" PRIMARY KEY (id),
    CONSTRAINT "FK_hero_media_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE promotional_panel (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    image_url text,
    link_url text,
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_promotional_panel" PRIMARY KEY (id),
    CONSTRAINT "FK_promotional_panel_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE sales_request (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    make character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    year integer NOT NULL,
    kilometers integer NOT NULL,
    additional_message text,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_sales_request" PRIMARY KEY (id),
    CONSTRAINT "FK_sales_request_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE vehicle (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    make character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    year integer NOT NULL,
    price numeric(10,2) NOT NULL,
    mileage integer NOT NULL,
    condition character varying(10) NOT NULL,
    status character varying(10) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    images jsonb NOT NULL DEFAULT ('[]'::jsonb),
    easycars_stock_number character varying(100),
    easycars_yard_code character varying(50),
    easycars_vin character varying(17),
    easycars_raw_data jsonb,
    data_source character varying(20) NOT NULL DEFAULT 'Manual',
    last_synced_from_easycars timestamp with time zone,
    exterior_color character varying(50),
    interior_color character varying(50),
    body character varying(50),
    fuel_type character varying(50),
    gear_type character varying(50),
    engine_capacity character varying(50),
    door_count integer,
    features jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_vehicle" PRIMARY KEY (id),
    CONSTRAINT "CK_vehicle_data_source" CHECK (data_source IN ('Manual', 'EasyCars', 'Import')),
    CONSTRAINT "FK_vehicle_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE TABLE easycars_sync_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    credential_id integer,
    sync_type character varying(20) NOT NULL,
    sync_direction character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    started_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    completed_at timestamp with time zone,
    records_processed integer NOT NULL DEFAULT 0,
    records_created integer NOT NULL DEFAULT 0,
    records_updated integer NOT NULL DEFAULT 0,
    records_failed integer NOT NULL DEFAULT 0,
    error_message text,
    error_details text,
    request_payload jsonb,
    response_summary jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_easycars_sync_logs" PRIMARY KEY (id),
    CONSTRAINT "CK_sync_logs_completed_at" CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT "CK_sync_logs_status" CHECK (status IN ('Success', 'Failed', 'Warning', 'InProgress')),
    CONSTRAINT "CK_sync_logs_sync_direction" CHECK (sync_direction IN ('Inbound', 'Outbound')),
    CONSTRAINT "CK_sync_logs_sync_type" CHECK (sync_type IN ('Stock', 'Lead')),
    CONSTRAINT "FK_easycars_sync_logs_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE,
    CONSTRAINT "FK_easycars_sync_logs_dealership_easycars_credentials_credenti~" FOREIGN KEY (credential_id) REFERENCES dealership_easycars_credentials (id) ON DELETE SET NULL
);

CREATE TABLE lead (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    vehicle_id integer,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    message text NOT NULL,
    status character varying(20) NOT NULL,
    easycars_lead_number character varying(100),
    easycars_customer_no character varying(100),
    easycars_raw_data jsonb,
    data_source character varying(20) NOT NULL DEFAULT 'Manual',
    last_synced_to_easycars timestamp with time zone,
    last_synced_from_easycars timestamp with time zone,
    vehicle_interest_type character varying(50),
    finance_interested boolean NOT NULL DEFAULT FALSE,
    rating character varying(20),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_lead" PRIMARY KEY (id),
    CONSTRAINT "CK_lead_data_source" CHECK (data_source IN ('Manual', 'EasyCars', 'WebForm')),
    CONSTRAINT "FK_lead_dealership_dealership_id" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE,
    CONSTRAINT "FK_lead_vehicle_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE SET NULL
);

CREATE INDEX idx_app_user_dealership_id ON app_user (dealership_id);

CREATE UNIQUE INDEX idx_app_user_username ON app_user (username);

CREATE INDEX "IX_blog_dealership_id" ON blog (dealership_id);

CREATE INDEX idx_blog_post_dealership_id ON blog_post (dealership_id);

CREATE INDEX idx_blog_post_slug ON blog_post (slug);

CREATE UNIQUE INDEX "IX_blog_post_dealership_id_slug" ON blog_post (dealership_id, slug);

CREATE UNIQUE INDEX idx_dealership_website_url ON dealership (website_url);

CREATE INDEX idx_easycars_credentials_active ON dealership_easycars_credentials (is_active) WHERE is_active = true;

CREATE UNIQUE INDEX idx_easycars_credentials_dealership ON dealership_easycars_credentials (dealership_id);

CREATE INDEX "IX_design_templates_dealership_id" ON design_templates (dealership_id);

CREATE INDEX idx_sync_logs_dealership ON easycars_sync_logs (dealership_id);

CREATE INDEX idx_sync_logs_started_at ON easycars_sync_logs (started_at DESC);

CREATE INDEX idx_sync_logs_status ON easycars_sync_logs (status);

CREATE INDEX idx_sync_logs_sync_type ON easycars_sync_logs (sync_type);

CREATE INDEX "IX_easycars_sync_logs_credential_id" ON easycars_sync_logs (credential_id);

CREATE INDEX "IX_hero_media_dealership_id" ON hero_media (dealership_id);

CREATE INDEX idx_lead_created_at ON lead (created_at DESC);

CREATE INDEX idx_lead_dealership_id ON lead (dealership_id);

CREATE INDEX idx_leads_data_source ON lead (data_source);

CREATE INDEX idx_leads_easycars_lead ON lead (easycars_lead_number) WHERE easycars_lead_number IS NOT NULL;

CREATE INDEX "IX_lead_vehicle_id" ON lead (vehicle_id);

CREATE INDEX "IX_promotional_panel_dealership_id" ON promotional_panel (dealership_id);

CREATE INDEX idx_sales_request_created_at ON sales_request (created_at DESC);

CREATE INDEX idx_sales_request_dealership_id ON sales_request (dealership_id);

CREATE INDEX idx_vehicle_dealership_id ON vehicle (dealership_id);

CREATE INDEX idx_vehicle_dealership_status ON vehicle (dealership_id, status);

CREATE INDEX idx_vehicle_status ON vehicle (status);

CREATE INDEX idx_vehicles_data_source ON vehicle (data_source);

CREATE INDEX idx_vehicles_easycars_stock ON vehicle (easycars_stock_number) WHERE easycars_stock_number IS NOT NULL;

CREATE INDEX idx_vehicles_easycars_vin ON vehicle (easycars_vin) WHERE easycars_vin IS NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260224101946_AddEasyCarsIntegration', '8.0.11');

COMMIT;

