-- Script to add EasyCars Integration schema to existing database
-- Story 1.1: Database Schema for EasyCars Integration

BEGIN;

-- 1. Create dealership_easycars_credentials table
CREATE TABLE IF NOT EXISTS dealership_easycars_credentials (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    account_number_encrypted text NOT NULL,
    account_secret_encrypted text NOT NULL,
    encryption_iv text NOT NULL,
    environment character varying(20) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    yard_code character varying(50),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    last_synced_at timestamp with time zone,
    CONSTRAINT "PK_dealership_easycars_credentials" PRIMARY KEY (id),
    CONSTRAINT "CK_easycars_credentials_environment" CHECK (environment IN ('Test', 'Production')),
    CONSTRAINT "FK_dealership_easycars_credentials_dealerships" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_easycars_credentials_dealership ON dealership_easycars_credentials(dealership_id);
CREATE INDEX idx_easycars_credentials_active ON dealership_easycars_credentials(is_active) WHERE is_active = true;

-- 2. Create easycars_sync_logs table
CREATE TABLE IF NOT EXISTS easycars_sync_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dealership_id integer NOT NULL,
    credential_id integer,
    sync_type character varying(20) NOT NULL,
    sync_direction character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    started_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    completed_at timestamp with time zone,
    records_processed integer NOT NULL DEFAULT 0,
    records_created integer NOT NULL DEFAULT 0,
    records_updated integer NOT NULL DEFAULT 0,
    records_failed integer NOT NULL DEFAULT 0,
    error_message text,
    error_details text,
    request_payload jsonb,
    response_summary jsonb,
    CONSTRAINT "PK_easycars_sync_logs" PRIMARY KEY (id),
    CONSTRAINT "CK_sync_logs_sync_type" CHECK (sync_type IN ('Stock', 'Lead')),
    CONSTRAINT "CK_sync_logs_sync_direction" CHECK (sync_direction IN ('Inbound', 'Outbound')),
    CONSTRAINT "CK_sync_logs_status" CHECK (status IN ('Success', 'Failed', 'Warning', 'InProgress')),
    CONSTRAINT "CK_sync_logs_completed_at" CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT "FK_easycars_sync_logs_dealerships" FOREIGN KEY (dealership_id) REFERENCES dealership (id) ON DELETE CASCADE,
    CONSTRAINT "FK_easycars_sync_logs_credentials" FOREIGN KEY (credential_id) REFERENCES dealership_easycars_credentials (id) ON DELETE SET NULL
);

CREATE INDEX idx_sync_logs_dealership ON easycars_sync_logs(dealership_id);
CREATE INDEX idx_sync_logs_status ON easycars_sync_logs(status);
CREATE INDEX idx_sync_logs_started_at ON easycars_sync_logs(started_at DESC);
CREATE INDEX idx_sync_logs_sync_type ON easycars_sync_logs(sync_type);

-- 3. Extend vehicle table with EasyCars columns
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'easycars_stock_number') THEN
        ALTER TABLE vehicle ADD COLUMN easycars_stock_number character varying(100);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'easycars_yard_code') THEN
        ALTER TABLE vehicle ADD COLUMN easycars_yard_code character varying(50);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'easycars_vin') THEN
        ALTER TABLE vehicle ADD COLUMN easycars_vin character varying(17);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'easycars_raw_data') THEN
        ALTER TABLE vehicle ADD COLUMN easycars_raw_data jsonb;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'data_source') THEN
        ALTER TABLE vehicle ADD COLUMN data_source character varying(20) NOT NULL DEFAULT 'Manual';
        ALTER TABLE vehicle ADD CONSTRAINT "CK_vehicle_data_source" CHECK (data_source IN ('Manual', 'EasyCars', 'Import'));
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'last_synced_from_easycars') THEN
        ALTER TABLE vehicle ADD COLUMN last_synced_from_easycars timestamp with time zone;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'exterior_color') THEN
        ALTER TABLE vehicle ADD COLUMN exterior_color character varying(50);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'interior_color') THEN
        ALTER TABLE vehicle ADD COLUMN interior_color character varying(50);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'body') THEN
        ALTER TABLE vehicle ADD COLUMN body character varying(50);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'fuel_type') THEN
        ALTER TABLE vehicle ADD COLUMN fuel_type character varying(50);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'gear_type') THEN
        ALTER TABLE vehicle ADD COLUMN gear_type character varying(50);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'engine_capacity') THEN
        ALTER TABLE vehicle ADD COLUMN engine_capacity character varying(50);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'door_count') THEN
        ALTER TABLE vehicle ADD COLUMN door_count integer;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'vehicle' AND column_name = 'features') THEN
        ALTER TABLE vehicle ADD COLUMN features jsonb;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_vehicle_easycars_stock ON vehicle(easycars_stock_number) WHERE easycars_stock_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_vehicle_data_source ON vehicle(data_source);
CREATE INDEX IF NOT EXISTS idx_vehicle_easycars_vin ON vehicle(easycars_vin) WHERE easycars_vin IS NOT NULL;

-- 4. Extend lead table with EasyCars columns
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'easycars_lead_number') THEN
        ALTER TABLE lead ADD COLUMN easycars_lead_number character varying(100);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'easycars_customer_no') THEN
        ALTER TABLE lead ADD COLUMN easycars_customer_no character varying(100);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'easycars_raw_data') THEN
        ALTER TABLE lead ADD COLUMN easycars_raw_data jsonb;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'data_source') THEN
        ALTER TABLE lead ADD COLUMN data_source character varying(20) NOT NULL DEFAULT 'Manual';
        ALTER TABLE lead ADD CONSTRAINT "CK_lead_data_source" CHECK (data_source IN ('Manual', 'EasyCars', 'WebForm'));
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'last_synced_to_easycars') THEN
        ALTER TABLE lead ADD COLUMN last_synced_to_easycars timestamp with time zone;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'last_synced_from_easycars') THEN
        ALTER TABLE lead ADD COLUMN last_synced_from_easycars timestamp with time zone;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'vehicle_interest_type') THEN
        ALTER TABLE lead ADD COLUMN vehicle_interest_type character varying(50);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'finance_interested') THEN
        ALTER TABLE lead ADD COLUMN finance_interested boolean DEFAULT false;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lead' AND column_name = 'rating') THEN
        ALTER TABLE lead ADD COLUMN rating character varying(20);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_lead_easycars_lead ON lead(easycars_lead_number) WHERE easycars_lead_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_lead_data_source ON lead(data_source);

COMMIT;
